{% set python_min = python_min|default("3.7") %}
{% set name = "check-internet-speed" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/check-internet-speed-{{ version }}.tar.gz
  sha256: 8be5c80f0d1f29e07529479cc40b3f2936196cd21be74d31495a818f981af917

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - setuptools
    - python  {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - check_internet_speed
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sujitmandal/check-internet-speed
  summary: checking internet upload and download speed.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/sujitmandal/check-internet-speed/
  dev_url: https://github.com/sujitmandal/check-internet-speed/

extra:
  recipe-maintainers:
    - sujitmandal
